database_password = None
ALLOW_PFP_UPLOAD = False
ALLOW_UPDATE_CHANNEL = False
ALLOW_AUTHORIZED_USERS_UPDATE_CHANNEL = True
ALLOW_ADD_YOUTUBE_VIDEO = False
ALLOW_AUTHORIZED_USERS_ADD_YOUTUBE_VIDEO = True
